ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chat/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import user_list, message_list, index,chat_view, register, message_view

urlpatterns = [
    path('', index, name = 'index' ),
    path('register', register, name = 'register'),
    path('chat/', chat_view, name = 'chats' ),
    path('chat/<int:sender>/<int:receiver>', message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', message_list, name='message-detail'),
    path('api/messages/', message_list, name= 'message-list'),
    path('api/users/', user_list, name='users'),
    path('api/users/<int:pk>/', user_list, name='user-detail'),
    path('logout', LogoutView.as_view(next_page = 'index'), name='logout'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models  import User

# Create your models here.

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length = 1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-timestamp']

chat/views.py
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Message
from .serializers import MessageSerializer, UserSerializer
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login


# Create your views here.
# User view
@csrf_exempt
def user_list(request, pk=None):
    if request.method=='GET':
        if pk:
            users = User.objects.filter(id=pk)
        else:
            users = User.objects.all()
        serializer = UserSerializer(users, many=True, context = {'request':request})
        return JsonResponse(serializer.data, safe=False)

    elif request.method=='POST':
        data = JSONParser().parse(request)
        serializer = UserSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

# Message list View
@csrf_exempt
def message_list(request, sender=None, receiver=None):
    if request.method=='GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id = receiver)
        serializer = MessageSerializer(messages, many=True, context={'request':request})
        return JsonResponse(serializer.data, safe=False)
    elif request.method=='POST':
        data =JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

# index view
def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method=='GET':
        return render(request, 'index.html', {})
    if request.method == 'POST':
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')

# chats view
def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == 'GET':
        return render(request, 'chat.html', {'users': User.objects.exclude(username=request.user.username)})
    

# register view
def register(request):
    if request.user.is_authenticated:
        return redirect('index')
    return render(request, 'register.html', {})

# message view

def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == 'GET':
        return render(request, 'message.html', {
            'users': User.objects.exclude(username = request.user.username),
            'receiver': User.objects.get(id=receiver),
            'messages': Message.objects.filter(sender_id=sender, receiver_id =receiver) |
                        Message.objects.filter(sender_id=receiver, receiver_id=sender)
        })

templates/chat.html
{% extends 'index.html' %}
{% block body %}
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">Chat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% for user in users %}
                <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg" class="col s4">
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}
                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving, set global variables to be used by the 'receive' function
        sender_id = "{{ receiver.id }}"; //Context variable for receiver
        receiver_id = "{{ request.user.id }}"; //Context variable for current logged in user
        //For sending
        $(function () {
            scrolltoend(); // Function to show the latest message, which is at the bottom of the message box, by scrolling to the end
            //Handling the submit event to send the message.
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val()); //Send function will be defined within 'chat.js'
                message.val(''); //Clear content of the the input field after sending
            })
        })
    </script>
{% endblock %}

templates/index.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>
    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2>Chat</h2>
            <p>A simple Chat App using DjangoRestFramework</p>
            {% comment %} <div class="chip">
                <img src="https://opbeat.com/docs/static/images/stacks/logo_django_alt.svg" class="white">
                Django
            </div>
            <div class="chip">
                <img src="http://materializecss.com/res/materialize.svg" class="white">
                MaterializeCSS
            </div> {% endcomment %}
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>
  </html>

templates/message.html
{% extends 'chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    //Highlighting the user that is currently selected for chatting in the users list
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function at an interval of 1 second to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/register.html
{% extends 'index.html' %}
{% block form %} 
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input name="username" id="id_username" type="text" class="validate invalid">
                <label for="id_username" data-error="Username already taken">Username</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="id_password" type="password">
                <label for="id_password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password2" id="id_password2" type="password">
                <label for="id_password2">Repeat Password</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button class="btn blue waves-effect waves-light pull-s12">Register</button>
            </div>
            </div>
        </div>
    </form>
    <script>
    //Script for validating user registration.
    $(function () {
        $('#register-form').on('submit', function (event) {
            event.preventDefault(); //Prevent the default behavior on submit.
            var username = $('#id_username').val();
            var password;
            if(username !== '') //Check if username in not blank
            {
                password = $('#id_password').val();
                if(password !== '' && password === $('#id_password2').val()) //Check if password is not blank and matches with the confirmation.
                {
                    register(username, password); //Calling register function, which we will define in 'chat.js'
                }
                else{
                    alert("The passwords doesn't match!");
                }
            }
            else
                alert("Please enter a valid username!");
        })
    })
    </script>
{% endblock %}